import { test, expect, type Page } from '@playwright/test';
import { createCampaign } from '../../campaigns/model';
import { createSection } from '../../blocks/registry';
import { defaultBrand } from '../../data/brand';

async function seed(page: Page, legacy = false) {
  const a = createSection('heroEditorial'), b = createSection('centeredText'), c = createSection('cta');
  a.content.pt.title = 'Pedra natural'; a.content.pt.text = 'Texto editorial original';
  b.content.pt.title = 'Segundo bloco'; c.content.pt.label = 'Fale conosco'; c.content.pt.link = 'https://example.com';
  const campaign = createCampaign({ title: 'Canvas de prova', ...(legacy ? {} : { sections: [a, b, c] }) });
  campaign.content.pt.headline = 'Título antigo';
  await page.addInitScript(data => { if (!sessionStorage.getItem('canvas-seeded')) { localStorage.setItem('granistone-mail-studio:v2', JSON.stringify(data)); sessionStorage.setItem('canvas-seeded', '1'); } }, { version: 2, campaigns: [campaign], brand: defaultBrand });
  await page.goto('/'); await page.getByRole('button', { name: campaign.title, exact: true }).click();
  return campaign;
}
test('continuous inline typing, marks, alignment, multiline, languages, undo and reload', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await seed(page); await page.setViewportSize({ width: 1440, height: 900 });
  const title = page.locator('.visual-email').getByRole('textbox', { name: 'Título do bloco', exact: true }).first();
  await title.fill('Granito'); await title.press('End');
  await title.pressSequentially(' brasileiro com beleza natural', { delay: 100 });
  await expect(title).toBeFocused(); await expect(title).toHaveText('Granito brasileiro com beleza natural');
  await title.press('Control+a'); await page.getByRole('toolbar', { name: 'Formatação da seleção' }).getByRole('button', { name: 'Negrito', exact: true }).click();
  await expect(title.locator('strong')).toHaveText('Granito brasileiro com beleza natural');
  await page.getByRole('button', { name: 'Alinhar texto à direita', exact: true }).click();
  await expect(title.locator('p')).toHaveCSS('text-align', 'right');
  const body = page.locator('.visual-email').getByRole('textbox', { name: 'Texto do bloco', exact: true }).first();
  await body.fill('Linha um'); await body.press('Enter'); await body.pressSequentially('Linha dois');
  await expect(body.locator('p')).toHaveCount(2);
  await page.locator('.editor-global-tools').getByRole('button', { name: 'ENGLISH' }).click();
  await title.fill('English title');
  await page.locator('.editor-global-tools').getByRole('button', { name: 'ESPAÑOL' }).click(); await title.fill('Título español');
  await page.locator('.editor-global-tools').getByRole('button', { name: 'PORTUGUÊS' }).click();
  await expect(title).toHaveText('Granito brasileiro com beleza natural');
  await page.getByRole('button', { name: 'Visualizar final', exact: true }).click();
  const frame = page.frameLocator('.preview-stage iframe');
  await expect(frame.locator('h2 strong').first()).toHaveText('Granito brasileiro com beleza natural');
  await expect(frame.locator('[contenteditable], [data-canvas-block], [data-section-id]')).toHaveCount(0);
  await page.getByRole('button', { name: 'Preview mobile' }).click();
  await expect.poll(() => frame.locator('html').evaluate(e => e.scrollWidth)).toBeLessThanOrEqual(375);
  await page.getByRole('button', { name: 'Editar no canvas' }).click();
  await page.reload(); await page.getByRole('button', { name: 'Canvas de prova', exact: true }).click();
  await expect(title.locator('strong')).toHaveText('Granito brasileiro com beleza natural');
  await expect(body.locator('p')).toHaveCount(2);
  await page.setViewportSize({ width: 1366, height: 768 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await title.scrollIntoViewIfNeeded(); await title.click(); await title.press('Control+a');
  await page.screenshot({ path: 'test-results/canvas-desktop.png' }); expect(errors).toEqual([]);
});
test('insert between blocks, duplicate, delete, undo, redo, hide and pointer reorder', async ({ page }) => {
  await seed(page);
  const cards = page.locator('[data-canvas-block]');
  const firstId = await cards.first().getAttribute('data-canvas-block');
  await page.getByRole('button', { name: 'Inserir bloco na posição 2', exact: true }).click();
  await page.locator('.canvas-library').getByRole('button', { name: 'Divisor', exact: true }).click();
  await expect(cards).toHaveCount(4); await expect(cards.nth(1)).toHaveAttribute('aria-label', 'Bloco 2: Divisor');
  await cards.nth(1).getByRole('button', { name: 'Duplicar bloco', exact: true }).click();
  await expect(cards).toHaveCount(5); await expect(cards.nth(2)).toHaveClass(/selected/);
  await cards.nth(2).getByRole('button', { name: 'Remover bloco', exact: true }).click(); await expect(cards).toHaveCount(4);
  await page.getByRole('button', { name: '↶ Desfazer', exact: true }).click(); await expect(cards).toHaveCount(5);
  await page.getByRole('button', { name: '↷ Refazer', exact: true }).click(); await expect(cards).toHaveCount(4);
  await cards.first().focus(); await cards.first().getByRole('button', { name: 'Ocultar bloco' }).click();
  await expect(cards.first()).toHaveClass(/hidden-block/);
  await cards.first().getByRole('button', { name: 'Exibir bloco' }).click();
  await cards.nth(1).scrollIntoViewIfNeeded(); await cards.nth(1).hover();
  const grip = cards.nth(1).getByRole('button', { name: 'Arrastar bloco', exact: true });
  const handle = await grip.boundingBox(), target = await cards.nth(2).boundingBox();
  await page.mouse.move(handle!.x + 10, handle!.y + 12); await page.mouse.down();
  await page.mouse.move(target!.x + 200, target!.y + target!.height * .8, { steps: 20 }); await page.mouse.up();
  await expect(cards.nth(2)).toHaveAttribute('aria-label', 'Bloco 3: Divisor');
  await expect(cards.first()).toHaveAttribute('data-canvas-block', firstId!);
  await cards.nth(2).focus(); await page.keyboard.press('Delete'); await expect(cards).toHaveCount(3);
  await page.keyboard.press('Control+z'); await expect(cards).toHaveCount(4);
});
test('image replacement from canvas uses the existing picker and persists alt text', async ({ page }) => {
  await seed(page);
  await page.getByRole('button', { name: 'Editar Imagem do bloco', exact: true }).click();
  const inspector = page.getByRole('complementary', { name: 'Propriedades do elemento' });
  await inspector.getByRole('button', { name: 'Computador', exact: true }).click();
  await inspector.getByLabel('Carregar imagem do bloco', { exact: true }).setInputFiles('public/brand/granistone-logo.png');
  await inspector.getByLabel('Texto alternativo · imagem do bloco', { exact: true }).fill('Fotografia de teste');
  await expect(page.locator('.visual-email .canvas-picture img')).toHaveAttribute('alt', 'Fotografia de teste');
  await expect(page.locator('.visual-email .canvas-picture img')).toHaveAttribute('src', /^data:image/);
  await page.getByRole('button', { name: '↶ Desfazer', exact: true }).click();
  await page.getByRole('button', { name: '↷ Refazer', exact: true }).click();
  await page.reload(); await page.getByRole('button', { name: 'Canvas de prova', exact: true }).click();
  await expect(page.locator('.visual-email .canvas-picture img')).toHaveAttribute('alt', 'Fotografia de teste');
});
test('legacy title and body remain editable without automatic section conversion', async ({ page }) => {
  await seed(page, true);
  const title = page.locator('.visual-email').getByRole('textbox', { name: 'Título', exact: true });
  await title.fill('Campanha antiga revisada');
  await page.locator('.visual-email').getByRole('textbox', { name: 'Texto editorial', exact: true }).fill('Parágrafo direto no canvas');
  await page.getByRole('button', { name: 'Visualizar final', exact: true }).click();
  const frame = page.frameLocator('.preview-stage iframe'); await expect(frame.locator('h1')).toHaveText('Campanha antiga revisada');
  await expect(frame.getByText('Parágrafo direto no canvas', { exact: true })).toBeVisible();
  await page.reload(); await page.getByRole('button', { name: 'Canvas de prova', exact: true }).click();
  await expect(title).toHaveText('Campanha antiga revisada'); await expect(page.locator('[data-canvas-block]')).toHaveCount(0);
});

test('template creation, live synchronization and lease permissions cover the inline canvas', async ({ page, browser }) => {
  test.setTimeout(90000);
  const secondContext = await browser.newContext(), second = await secondContext.newPage();
  const authenticate = async (p: Page, id: string) => p.route('**/api/**', async route => route.fulfill({ response: await route.fetch({ headers: { ...route.request().headers(), 'oai-authenticated-user-id': id, 'oai-authenticated-user-email': 'local@studio.test', origin: 'https://studio.example.com', 'sec-fetch-site': 'same-origin' } }) }));
  await authenticate(page, 'canvas-owner'); await authenticate(second, 'canvas-collaborator');
  try {
    const name = `Canvas compartilhado ${Date.now()}`;
    await page.goto('/'); await page.getByRole('button', { name: 'Nova campanha', exact: true }).first().click();
    await page.getByLabel('Nome da campanha', { exact: true }).fill(name);
    await page.getByLabel('Template inicial', { exact: true }).selectOption('promo-impact');
    await page.getByRole('button', { name: 'Criar campanha', exact: true }).click();
    await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem');
    await page.locator('.edit-lease-bar').getByRole('button', { name: 'Editar', exact: true }).click();
    const title = page.locator('.visual-email').getByRole('textbox', { name: 'Título do bloco', exact: true }).first();
    await expect(title).toHaveAttribute('contenteditable', 'true');
    await second.goto('/'); await second.getByRole('button', { name, exact: true }).click();
    const other = second.locator('.visual-email').getByRole('textbox', { name: 'Título do bloco', exact: true }).first();
    await expect(other).toHaveAttribute('contenteditable', 'false');
    await title.fill('Título compartilhado'); await title.press('Control+a');
    await page.getByRole('toolbar', { name: 'Formatação da seleção' }).getByRole('button', { name: 'Negrito', exact: true }).click();
    await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem');
    await page.getByRole('button', { name: 'Salvar e encerrar edição' }).click();
    await expect(title).toHaveAttribute('contenteditable', 'false');
    await second.locator('.edit-lease-bar').getByRole('button', { name: 'Editar', exact: true }).click();
    await expect(other.locator('strong')).toHaveText('Título compartilhado');
    await expect(other).toHaveAttribute('contenteditable', 'true');
    await other.fill('Revisado por colaborador'); await expect(second.locator('.save-indicator')).toHaveText('Salvo na nuvem');
    await second.getByRole('button', { name: 'Salvar e encerrar edição' }).click();
    await page.reload(); await page.getByRole('button', { name, exact: true }).click();
    await expect(title).toHaveText('Revisado por colaborador'); await expect(title).toHaveAttribute('contenteditable', 'false');
  } finally { await secondContext.close(); }
});

test('paste sanitization, link editing, list formatting and review navigation work on canvas', async ({ page }) => {
  await seed(page); await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  const body = page.locator('.visual-email').getByRole('textbox', { name: 'Texto do bloco', exact: true }).first();
  await body.click(); await body.press('Control+a');
  await page.evaluate(async () => navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob(['<p><b>Conteúdo colado</b><img src="x" onerror="alert(1)"><script>alert(1)</script></p>'], { type: 'text/html' }) })]));
  await body.press('Control+v'); await expect(body.locator('strong')).toHaveText('Conteúdo colado'); await expect(body.locator('script,img')).toHaveCount(0);
  await body.press('Control+a'); const bubble = page.getByRole('toolbar', { name: 'Formatação da seleção' });
  await bubble.getByRole('button', { name: 'Link', exact: true }).click();
  await bubble.getByLabel('Endereço do link').fill('javascript:alert(1)'); await bubble.getByRole('button', { name: 'Aplicar', exact: true }).click();
  await expect(bubble.getByRole('alert')).toBeVisible();
  await bubble.getByLabel('Endereço do link').fill('https://granistone.com.br'); await bubble.getByRole('button', { name: 'Aplicar', exact: true }).click();
  await expect(body.locator('a')).toHaveAttribute('href', 'https://granistone.com.br');
  await body.press('Control+a'); await bubble.getByRole('button', { name: 'Lista', exact: true }).click(); await expect(body.locator('ul li')).toHaveCount(1);
  await page.getByRole('button', { name: 'Visualizar final', exact: true }).click();
  await expect(page.frameLocator('.preview-stage iframe').locator('a[href="https://granistone.com.br"]')).toHaveText('Conteúdo colado');
  await page.getByRole('button', { name: 'Revisar', exact: true }).click();
  const review = page.getByRole('dialog', { name: 'Revisão da campanha' });
  await review.getByRole('button', { name: 'Localizar no e-mail', exact: true }).first().click();
  await expect(review).toHaveCount(0); await expect(page.locator('.canvas-inspector')).toBeVisible();
});

test('contextual styles, spacing, color and block alignment share export and global history', async ({ page }) => {
  await seed(page);
  const card = page.locator('[data-canvas-block]').first(); await card.focus();
  await card.getByRole('button', { name: 'Propriedades do bloco', exact: true }).click();
  const inspector = page.locator('.canvas-inspector');
  await inspector.getByLabel('Aplicar estilo do bloco', { exact: true }).selectOption('premium');
  await expect(card.locator('.canvas-section-content')).toHaveCSS('background-color', 'rgb(17, 17, 17)');
  await expect(card.locator('.canvas-section-content')).toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(card.locator('.canvas-section-content')).toHaveCSS('padding', '40px');
  await inspector.getByRole('button', { name: 'Alinhar à direita', exact: true }).click();
  await inspector.getByLabel('Espaçamento interno', { exact: true }).focus(); await page.keyboard.press('ArrowRight');
  await expect(card.locator('.canvas-section-content')).toHaveCSS('padding', '44px');
  await page.getByRole('button', { name: '↶ Desfazer', exact: true }).click(); await expect(card.locator('.canvas-section-content')).toHaveCSS('padding', '40px');
  await page.getByRole('button', { name: '↷ Refazer', exact: true }).click(); await expect(card.locator('.canvas-section-content')).toHaveCSS('padding', '44px');
  await page.getByRole('button', { name: 'Visualizar final', exact: true }).click();
  const frame = page.frameLocator('.preview-stage iframe');
  await expect(frame.locator('td[style*="padding:44px"]').first()).toHaveAttribute('align', 'right');
  await expect(frame.locator('td[bgcolor="#111111"]').first()).toBeVisible();
  await page.getByRole('button', { name: 'Editar no canvas' }).click();
  await page.setViewportSize({ width: 1440, height: 900 });
  await card.scrollIntoViewIfNeeded(); await page.screenshot({ path: 'test-results/canvas-properties.png' });
});
