import { test, expect, type Page } from '@playwright/test';
import { createCampaign } from '../../campaigns/model';
import { defaultBrand } from '../../data/brand';
const auth = { 'oai-authenticated-user-id': 'design-owner', 'oai-authenticated-user-email': 'local@studio.test', origin: 'https://studio.example.com', 'sec-fetch-site': 'same-origin' };
async function authenticate(page: Page) {
  await page.route('**/api/**', async route => route.fulfill({ response: await route.fetch({ headers: { ...route.request().headers(), ...auth } }) }));
}
async function editing(page: Page) {
  await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem');
  await page.locator('.edit-lease-bar').getByRole('button', { name: 'Editar', exact: true }).click();
}
test('free blocks, saved library, campaign copy and shared custom templates work across two browsers', async ({ page, browser, request }) => {
  test.setTimeout(120000);
  const name = 'Design ' + Date.now(), blockName = name + ' bloco', templateName = name + ' template';
  const campaign = createCampaign({ title: name, sections: [] });
  expect((await request.post('/api/campaigns', { headers: auth, data: { campaign, requestId: crypto.randomUUID() } })).status()).toBe(201);
  await authenticate(page); await page.goto('/');
  await page.getByRole('button', { name, exact: true }).click(); await editing(page);
  await page.getByRole('button', { name: 'Adicionar bloco', exact: true }).click();
  const catalog = page.getByRole('dialog', { name: 'Adicionar bloco' });
  await expect(catalog.locator('.block-catalog button')).toHaveCount(16);
  await catalog.getByRole('button', { name: 'Texto centralizado', exact: true }).click();
  const cards = page.locator('.section-card');
  await cards.first().getByLabel('Título do bloco', { exact: true }).fill('Pedra natural');
  await cards.first().getByLabel('Texto do bloco', { exact: true }).fill('Conteúdo reutilizável');
  await cards.first().getByRole('button', { name: 'Duplicar bloco', exact: true }).click();
  await expect(cards).toHaveCount(2);
  await cards.nth(1).getByRole('button', { name: '02 · Texto centralizado' }).click();
  await cards.nth(1).getByLabel('Título do bloco', { exact: true }).fill('Segundo bloco');
  await cards.nth(1).getByRole('button', { name: 'Subir bloco' }).click();
  await expect(cards.first().getByLabel('Título do bloco', { exact: true })).toHaveValue('Segundo bloco');
  await cards.first().getByLabel('Ativar Texto centralizado').uncheck();
  await expect(page.frameLocator('.preview-stage iframe').getByRole('heading', { name: 'Segundo bloco' })).toHaveCount(0);
  await cards.first().getByRole('button', { name: 'Remover bloco', exact: true }).click();
  await page.getByRole('dialog', { name: 'Remover bloco' }).getByRole('button', { name: 'Remover bloco', exact: true }).click();
  await expect(cards).toHaveCount(1);
  await cards.first().getByRole('button', { name: 'Salvar bloco reutilizável' }).click();
  const saveBlock = page.getByRole('dialog', { name: 'Salvar bloco reutilizável' });
  await saveBlock.getByLabel('Nome', { exact: true }).fill(blockName);
  await saveBlock.getByRole('button', { name: 'Salvar na biblioteca' }).click();
  await expect(saveBlock).toHaveCount(0);
  await page.getByRole('button', { name: 'Inserir bloco salvo' }).click();
  const saved = page.getByRole('dialog', { name: 'Blocos Granistone' });
  await saved.locator('.saved-design-card').filter({ hasText: blockName }).getByRole('button', { name: 'Inserir bloco', exact: true }).click();
  await expect(cards).toHaveCount(2);
  await expect(cards.last().getByLabel('Título do bloco', { exact: true })).toHaveValue('Pedra natural');
  await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem');
  await page.getByRole('button', { name: 'Salvar como template', exact: true }).click();
  const saveTemplate = page.getByRole('dialog', { name: 'Salvar como template' });
  await saveTemplate.getByLabel('Nome', { exact: true }).fill(templateName);
  await saveTemplate.getByRole('button', { name: 'Salvar na biblioteca' }).click();
  await expect(saveTemplate).toHaveCount(0);
  await page.getByRole('button', { name: 'Duplicar campanha', exact: true }).click();
  await expect(page.getByRole('heading', { name: name + ' · cópia', exact: true })).toBeVisible();
  await expect(page.getByLabel('Status da campanha')).toHaveValue('Em produção');
  await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem');
  const ctx = await browser.newContext(), second = await ctx.newPage();
  try {
    await authenticate(second); await second.goto('/');
    await second.getByRole('button', { name: /Templates 9/ }).click();
    const tile = second.locator('.saved-design-card').filter({ hasText: templateName });
    await expect(tile).toBeVisible();
    await tile.getByRole('button', { name: 'Editar', exact: true }).click();
    const edit = second.getByRole('dialog', { name: 'Editar template', exact: true });
    await edit.getByRole('button', { name: 'Editar', exact: true }).click();
    await edit.getByLabel('Descrição', { exact: true }).fill('Compartilhado entre navegadores');
    await edit.getByRole('button', { name: 'Salvar na biblioteca' }).click();
    await expect(edit).toHaveCount(0);
    await expect(tile).toContainText('Compartilhado entre navegadores');
    await tile.getByRole('button', { name: 'Usar template', exact: true }).click();
    await expect(second.locator('.section-card')).toHaveCount(2);
    await expect(second.frameLocator('.preview-stage iframe').getByText('[Título do bloco]', { exact: true })).toHaveCount(2);
    await editing(second);
    await second.locator('.section-card').first().getByRole('button', { name: '01 · Texto centralizado' }).click();
    await second.getByLabel('Título do bloco', { exact: true }).fill('Campanha derivada');
    await expect(second.locator('.save-indicator')).toHaveText('Salvo na nuvem');
    await second.setViewportSize({ width: 390, height: 844 });
    expect(await second.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await second.screenshot({ path: 'test-results/design-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Voltar às campanhas' }).click();
    await page.getByRole('button', { name: /Templates 9/ }).click();
    await expect(page.locator('.saved-design-card').filter({ hasText: templateName })).toContainText('Compartilhado entre navegadores');
    await page.locator('.saved-design-card').filter({ hasText: templateName }).getByRole('button', { name: 'Duplicar', exact: true }).click();
    const copied = page.locator('.saved-design-card').filter({ has: page.getByRole('heading', { name: templateName + ' · cópia', exact: true }) });
    await copied.getByRole('button', { name: 'Excluir', exact: true }).click();
    await page.getByRole('dialog', { name: 'Excluir da biblioteca' }).getByRole('button', { name: 'Excluir da biblioteca' }).click();
    await expect(copied).toHaveCount(0);
  } finally { await ctx.close(); }
});

test('legacy conversion and solid, gradient, image backgrounds match exported HTML with fallback warnings', async ({ page, request }) => {
  test.setTimeout(90000);
  await authenticate(page); await page.goto('/');
  await page.getByRole('button', { name: 'Nova campanha', exact: true }).first().click();
  const title = 'Fundos ' + Date.now();
  await page.getByLabel('Nome da campanha', { exact: true }).fill(title);
  await page.getByRole('button', { name: 'Criar campanha', exact: true }).click(); await editing(page);
  await page.getByLabel('Headline', { exact: true }).fill('Composição mineral');
  await expect(page.frameLocator('.preview-stage iframe').getByRole('heading', { name: 'Composição mineral' })).toBeVisible();
  await page.getByRole('button', { name: 'Estrutura', exact: true }).click();
  await page.getByRole('button', { name: 'Usar blocos livres' }).click();
  await page.getByRole('button', { name: 'Converter estrutura', exact: true }).click();
  await expect(page.frameLocator('.preview-stage iframe').getByRole('heading', { name: 'Composição mineral' })).toBeVisible();
  await page.getByRole('button', { name: 'Fundos', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^Fundo do e-mail$/ }).click();
  await page.getByLabel('Fundo do e-mail · tipo').selectOption('none');
  await expect(page.frameLocator('.preview-stage iframe').locator('body > table')).not.toHaveAttribute('bgcolor');
  await page.getByLabel('Fundo do e-mail · tipo').selectOption('preset');
  await page.getByRole('group', { name: 'Presets de background' }).getByRole('button', { name: 'Preto Premium' }).click();
  await expect(page.frameLocator('.preview-stage iframe').locator('body > table')).toHaveAttribute('bgcolor', '#111111');
  await page.getByLabel('Fundo do e-mail · tipo').selectOption('solid');
  await page.getByLabel('Fundo do e-mail · cor · hexadecimal').fill('#AB1234');
  await expect(page.frameLocator('.preview-stage iframe').locator('body > table')).toHaveAttribute('bgcolor', '#AB1234');
  await page.getByLabel('Fundo do e-mail · tipo').selectOption('gradient');
  await page.getByLabel('Direção do gradiente').selectOption('diagonal');
  await page.getByLabel('Cor de fallback · hexadecimal').fill('#333333');
  await expect(page.frameLocator('.preview-stage iframe').locator('body > table')).toHaveAttribute('bgcolor', '#333333');
  await page.locator('summary').filter({ hasText: /^Fundo do conteúdo$/ }).click();
  await page.getByLabel('Fundo do conteúdo · tipo').selectOption('image');
  const contentBg = page.locator('.background-editor').filter({ has: page.locator('summary').filter({ hasText: /^Fundo do conteúdo$/ }) });
  await contentBg.getByRole('button', { name: 'Computador', exact: true }).click();
  await contentBg.locator('input[type="file"]').setInputFiles('public/brand/granistone-logo.png');
  await expect(contentBg.getByText('Imagem selecionada')).toBeVisible();
  await contentBg.getByLabel('Cor de fallback · hexadecimal').fill('#F5F3EF');
  await page.getByLabel('Ajuste da imagem').selectOption('contain');
  await page.getByLabel('Posição do background').selectOption('top');
  await expect(page.locator('.save-indicator')).toHaveText('Salvo na nuvem', { timeout: 15000 });
  await expect(page.frameLocator('.preview-stage iframe').locator('.email-container')).toHaveAttribute('background', /^https:\/\/studio\.example\.com\/assets\//);
  const shared = (await (await request.get('/api/campaigns', { headers: auth })).json()).find((r: { campaign: { title: string } }) => r.campaign.title === title);
  const input = { campaign: shared.campaign, language: 'pt', brand: { ...defaultBrand, assetBaseUrl: 'https://studio.example.com' } };
  const { html } = await (await request.post('/api/render', { headers: auth, data: input })).json();
  expect(html).toContain('linear-gradient(135deg'); expect(html).toContain('bgcolor="#333333"'); expect(html).toMatch(/background="https:\/\/studio\.example\.com\/assets\//);
  const preflight = await (await request.post('/api/preflight', { headers: auth, data: input })).json();
  expect(preflight.warnings.some((c: { message: string }) => c.message.includes('Outlook desktop'))).toBe(true);
  await page.screenshot({ path: 'test-results/design-desktop.png', fullPage: true });
});
