import { test, expect } from '@playwright/test';
import { createCampaign } from '../../campaigns/model';
import { defaultBrand } from '../../data/brand';

test('legacy material does not hide folder images; selection and crop preserve the exact preview', async ({ page }) => {
  const campaign = createCampaign({ title: 'Seleção e recorte', template: 'product-commercial', materialId: 'legacy-crystal-palace' });
  await page.addInitScript(value => localStorage.setItem('granistone-mail-studio:v2', JSON.stringify(value)), { version: 2, campaigns: [campaign], brand: defaultBrand });
  await page.goto('/');
  const source = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 600; canvas.height = 900;
    const context = canvas.getContext('2d')!;
    context.fillStyle = '#e04040'; context.fillRect(0, 0, 300, 900);
    context.fillStyle = '#2070c0'; context.fillRect(300, 0, 300, 450);
    context.fillStyle = '#30a060'; context.fillRect(300, 450, 300, 450);
    context.clearRect(230, 350, 140, 200);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  const photo = Buffer.from(source, 'base64');
  const assets = ['vertical', 'horizontal'].map((orientation, i) => ({ id: `photo-${i}`, name: i ? 'Amazonita horizontal' : 'Amazonita vertical', fileName: 'amazonita.png', mimeType: 'image/png', width: i ? 900 : 600, height: i ? 600 : 900, orientation, fileSize: photo.length, url: `https://images.example.com/photo-${i}.png`, alt: 'Amazonita do catálogo', category: 'material', folderPaths: ['Imagens Catálogo/Amazonita Amazon Green'], createdAt: '', updatedAt: '' }));
  await page.route('https://images.example.com/**', route => route.fulfill({ body: photo, contentType: 'image/png', headers: { 'Access-Control-Allow-Origin': '*' } }));
  await page.route('**/api/assets?**', route => route.fulfill({ json: assets }));
  await page.route('**/api/materials', route => route.fulfill({ json: [] }));
  await page.getByRole('button', { name: campaign.title, exact: true }).click();
  await expect(page.locator('.preview-stage iframe')).toHaveAttribute('aria-busy', 'false');
  const emailCanvas = page.locator('.visual-email');
  await page.getByRole('button', { name: 'Editar Imagem principal', exact: true }).click();
  const picker = page.getByRole('complementary', { name: 'Propriedades do elemento' });
  await picker.getByRole('button', { name: /Abrir biblioteca de imagens/ }).click();
  await picker.getByRole('button', { name: 'Imagens Catálogo 2 imagens', exact: true }).click();
  await picker.getByRole('button', { name: 'Amazonita Amazon Green 2 imagens', exact: true }).click();
  await expect(picker.locator('.asset-card')).toHaveCount(2);
  await expect(picker.getByLabel('Material', { exact: true })).toBeVisible();
  await expect(picker.getByLabel('Material', { exact: true })).toHaveValue('');
  await expect(picker.getByLabel('Orientação')).toHaveValue('');
  await picker.getByLabel('Orientação').selectOption('square');
  await expect(picker.getByText('Nenhuma imagem encontrada')).toBeVisible();
  await picker.getByRole('button', { name: 'Limpar filtros' }).click();
  await expect(picker.locator('.asset-card')).toHaveCount(2);
  await picker.locator('.asset-card').filter({ hasText: 'Amazonita vertical' }).getByRole('button', { name: 'Usar imagem' }).click();
  await expect(picker.getByLabel('Texto alternativo · imagem principal', { exact: true })).toHaveValue('Amazonita do catálogo');
  await expect(picker.locator('.image-current img')).toHaveAttribute('src', assets[0].url);
  await picker.getByRole('button', { name: 'Editar corte e tamanho' }).click();
  const crop = page.getByRole('dialog', { name: 'Editar corte da imagem', exact: true });
  await expect(crop.getByRole('button', { name: 'Salvar recorte' })).toBeEnabled();
  await expect(crop.locator('.crop-handle')).toHaveCount(8);
  const corner = (await crop.getByRole('button', { name: 'Arrastar canto inferior direito' }).boundingBox())!;
  await page.mouse.move(corner.x + corner.width / 2, corner.y + corner.height / 2);
  await page.mouse.down(); await page.mouse.move(corner.x + corner.width / 2 - 40, corner.y + corner.height / 2 - 30, { steps: 5 }); await page.mouse.up();
  expect(Number(await crop.getByLabel('Zoom', { exact: true }).inputValue())).toBeGreaterThan(1);
  const zoomAfterCorner = Number(await crop.getByLabel('Zoom', { exact: true }).inputValue());
  const edge = (await crop.getByRole('button', { name: 'Arrastar borda direita' }).boundingBox())!;
  await page.mouse.move(edge.x + edge.width / 2, edge.y + edge.height / 2);
  await page.mouse.down(); await page.mouse.move(edge.x + edge.width / 2 - 20, edge.y + edge.height / 2, { steps: 5 }); await page.mouse.up();
  expect(Number(await crop.getByLabel('Zoom', { exact: true }).inputValue())).toBeGreaterThan(zoomAfterCorner);
  const selection = (await crop.locator('.crop-selection').boundingBox())!;
  await page.mouse.move(selection.x + selection.width / 2, selection.y + selection.height / 2);
  await page.mouse.down(); await page.mouse.move(selection.x + selection.width / 2 + 20, selection.y + selection.height / 2 + 20, { steps: 5 }); await page.mouse.up();
  expect(Number(await crop.getByLabel('Posição horizontal', { exact: true }).inputValue())).toBeGreaterThan(0);
  await crop.getByRole('button', { name: 'Redefinir recorte' }).click();
  await crop.getByLabel('Zoom', { exact: true }).fill('1.5');
  const canvas = crop.locator('canvas');
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 30, bounds.y + bounds.height / 2 + 20, { steps: 5 }); await page.mouse.up();
  expect(Number(await crop.getByLabel('Posição horizontal', { exact: true }).inputValue())).toBeLessThan(50);
  expect(Number(await crop.getByLabel('Posição vertical', { exact: true }).inputValue())).toBeLessThan(50);
  await crop.getByRole('button', { name: 'Redefinir recorte' }).click();
  await expect(crop.getByLabel('Zoom', { exact: true })).toHaveValue('1');
  await crop.getByLabel('Zoom', { exact: true }).fill('1.5');
  await crop.getByLabel('Posição horizontal', { exact: true }).fill('40');
  await crop.getByLabel('Posição vertical', { exact: true }).fill('60');
  const preview = await canvas.evaluate((element: HTMLCanvasElement) => element.toDataURL('image/png'));
  let upload: Buffer | null = null; let attempts = 0;
  await page.route('**/api/assets', async route => {
    attempts++;
    if (attempts === 1) return route.fulfill({ status: 503, json: { error: 'Falha temporária no envio' } });
    upload = route.request().postDataBuffer();
    expect(route.request().headers()['content-type']).toBe('image/png');
    await route.fulfill({ json: { ...assets[0], id: 'crop', url: 'https://images.example.com/crop.png', width: 1200, height: 700 } });
  });
  await crop.getByRole('button', { name: 'Salvar recorte' }).click();
  await expect(crop.getByRole('alert')).toHaveText('Falha temporária no envio');
  await expect(crop.getByRole('button', { name: 'Salvar recorte' })).toBeEnabled();
  await expect(crop.getByLabel('Posição vertical', { exact: true })).toHaveValue('60');
  await crop.screenshot({ path: 'test-results/crop-editor.png' });
  await crop.getByRole('button', { name: 'Salvar recorte' }).click();
  await expect(crop).toHaveCount(0);
  expect(upload).not.toBeNull();
  const difference = await page.evaluate(async ({ preview, saved }) => {
    const decode = async (src: string) => {
      const image = new Image(); image.src = src; await image.decode();
      const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height;
      const context = canvas.getContext('2d')!; context.drawImage(image, 0, 0);
      return { width: image.width, height: image.height, pixels: context.getImageData(0, 0, image.width, image.height).data };
    };
    const [a, b] = await Promise.all([decode(preview), decode(saved)]);
    let maxDifference = 0;
    for (let index = 0; index < a.pixels.length; index++) maxDifference = Math.max(maxDifference, Math.abs(a.pixels[index] - b.pixels[index]));
    return { width: b.width, height: b.height, maxDifference };
  }, { preview, saved: `data:image/png;base64,${upload!.toString('base64')}` });
  expect(difference).toEqual({ width: 1200, height: 700, maxDifference: 0 });
  await expect(picker.locator('.image-current img')).toHaveAttribute('src', 'https://images.example.com/crop.png');
  await page.setViewportSize({ width: 1366, height: 768 });
  expect(await picker.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(false);
  await picker.screenshot({ path: 'test-results/image-picker-desktop.png' });
  await page.getByRole('button', { name: 'Recolher propriedades' }).click();
  await page.getByRole('button', { name: 'ENGLISH', exact: true }).click();
  await expect(emailCanvas.locator('.canvas-picture img').first()).toHaveAttribute('src', 'https://images.example.com/crop.png');
});

test('crop ratio starts locked and a custom selection saves without stretching', async ({ page }) => {
  const campaign = createCampaign({ title: 'Recorte livre', template: 'product-commercial' });
  await page.addInitScript(value => localStorage.setItem('granistone-mail-studio:v2', JSON.stringify(value)), { version: 2, campaigns: [campaign], brand: defaultBrand });
  await page.goto('/');
  const source = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 600; canvas.height = 900;
    const context = canvas.getContext('2d')!;
    context.fillStyle = '#2370aa'; context.fillRect(0, 0, 600, 900);
    context.clearRect(100, 100, 100, 100);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  const photo = Buffer.from(source, 'base64');
  const asset = { id: 'photo', name: 'Pedra', fileName: 'pedra.png', mimeType: 'image/png', width: 600, height: 900, orientation: 'vertical', fileSize: photo.length, url: 'https://images.example.com/pedra.png', alt: 'Pedra natural', category: 'material', folderPaths: [], createdAt: '', updatedAt: '' };
  await page.route('https://images.example.com/**', route => route.fulfill({ body: photo, contentType: 'image/png', headers: { 'Access-Control-Allow-Origin': '*' } }));
  await page.route('**/api/assets?**', route => route.fulfill({ json: [asset] }));
  await page.route('**/api/materials', route => route.fulfill({ json: [] }));
  await page.getByRole('button', { name: campaign.title, exact: true }).click();
  await expect(page.locator('.preview-stage iframe')).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Editar Imagem principal', exact: true }).click();
  const picker = page.getByRole('complementary', { name: 'Propriedades do elemento' });
  await picker.getByRole('button', { name: /Abrir biblioteca de imagens/ }).click();
  await picker.locator('.asset-card').getByRole('button', { name: 'Usar imagem' }).click();
  await picker.getByRole('button', { name: 'Editar corte e tamanho' }).click();
  const crop = page.getByRole('dialog', { name: 'Editar corte da imagem', exact: true });
  const ratio = crop.getByRole('button', { name: 'Manter proporção recomendada' });
  await expect(ratio).toHaveAttribute('aria-pressed', 'true');
  await expect(crop.getByText('Desmarque a proporção para criar um recorte personalizado arrastando as bordas ou os cantos.')).toBeVisible();
  await ratio.click();
  await expect(ratio).toHaveAttribute('aria-pressed', 'false');
  const before = await crop.locator('.crop-selection').boundingBox();
  const edge = (await crop.getByRole('button', { name: 'Arrastar borda direita' }).boundingBox())!;
  await page.mouse.move(edge.x + edge.width / 2, edge.y + edge.height / 2);
  await page.mouse.down(); await page.mouse.move(edge.x + edge.width / 2 - 80, edge.y + edge.height / 2, { steps: 5 }); await page.mouse.up();
  const after = await crop.locator('.crop-selection').boundingBox();
  expect(after!.width).toBeLessThan(before!.width - 40);
  expect(Math.abs(after!.height - before!.height)).toBeLessThan(2);
  const preview = await crop.locator('canvas').evaluate((canvas: HTMLCanvasElement) => ({ width: canvas.width, height: canvas.height, image: canvas.toDataURL('image/png') }));
  expect(preview.width / preview.height).toBeCloseTo(after!.width / after!.height, 2);
  expect(preview.height).not.toBe(700);
  let upload: Buffer | null = null; let uploadMime = '';
  await page.route('**/api/assets', route => {
    upload = route.request().postDataBuffer();
    uploadMime = route.request().headers()['content-type'];
    expect(['image/png', 'image/jpeg']).toContain(uploadMime);
    return route.fulfill({ json: { ...asset, id: 'custom-crop', url: 'https://images.example.com/custom-crop.png', width: preview.width, height: preview.height } });
  });
  await crop.getByRole('button', { name: 'Salvar recorte' }).click();
  await expect(crop).toHaveCount(0);
  expect(upload).not.toBeNull();
  const saved = await page.evaluate(async data => {
    const image = new Image(); image.src = data; await image.decode();
    return { width: image.width, height: image.height };
  }, `data:${uploadMime};base64,${upload!.toString('base64')}`);
  expect(saved).toEqual({ width: preview.width, height: preview.height });
  await expect(picker.locator('.image-current img')).toHaveAttribute('src', 'https://images.example.com/custom-crop.png');
});
