import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createCampaign } from '../../campaigns/model';
import { defaultBrand } from '../../data/brand';

test('real layouts, clickable slots, large local photo, web image and portable export', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.route('https://images.example.com/material.png', (route) => route.fulfill({ path: 'public/brand/granistone-logo.png', contentType: 'image/png' }));
  await page.goto('/');
  await page.getByRole('button', { name: /Templates/ }).first().click();
  await expect(page.locator('.template-live-preview iframe')).toHaveCount(5);
  await page.screenshot({ path: 'test-results/layout-library.png', fullPage: true });
  await page.getByRole('button', { name: /Produto · Comercial.*Usar template/ }).click();
  await page.getByLabel('Nome da campanha', { exact: true }).fill('Layout com fotos');
  await page.getByRole('button', { name: 'Criar campanha', exact: true }).click();
  const frame = page.frameLocator('.preview-stage iframe');
  await expect(frame.getByRole('button', { name: 'Adicionar foto do produto' })).toBeVisible();
  const split = frame.locator('.stack-col');
  await expect(split).toHaveCount(2);
  await page.screenshot({ path: 'test-results/commercial-empty-slots.png', fullPage: true });
  await frame.getByRole('button', { name: 'Adicionar foto do produto' }).click();
  await expect(page.getByRole('dialog', { name: 'Imagem principal', exact: true })).toBeVisible();
  const base64 = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 2000; canvas.height = 1400;
    const context = canvas.getContext('2d')!;
    const pixels = context.createImageData(canvas.width, canvas.height);
    let seed = 1977;
    const randomByte = () => { seed ^= seed << 13; seed ^= seed >>> 17; seed ^= seed << 5; return seed & 255; };
    for (let i = 0; i < pixels.data.length; i += 4) {
      pixels.data[i] = randomByte();
      pixels.data[i + 1] = randomByte();
      pixels.data[i + 2] = randomByte();
      pixels.data[i + 3] = 255;
    }
    context.putImageData(pixels, 0, 0);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  const file = Buffer.from(base64, 'base64');
  expect(file.length).toBeGreaterThan(1_000_000);
  await page.locator('dialog input[type=file]').setInputFiles({ name: 'foto-grande.png', mimeType: 'image/png', buffer: file });
  await expect(page.getByText('foto-grande.png · imagem pronta')).toBeVisible();
  await page.getByRole('dialog').getByLabel('Texto alternativo · imagem principal', { exact: true }).fill('Foto carregada do computador');
  await page.getByRole('button', { name: 'Concluir', exact: true }).click();
  await expect(frame.getByRole('img', { name: 'Foto carregada do computador' })).toBeVisible();
  const source = await frame.getByRole('img', { name: 'Foto carregada do computador' }).getAttribute('src');
  expect(source).toMatch(/^data:image\/jpeg/);
  expect(source!.length).toBeLessThan(1_000_000);
  await page.getByRole('button', { name: 'ENGLISH', exact: true }).click();
  await expect(frame.locator('[data-image-slot="hero"] img')).toHaveAttribute('src', source!);
  await page.getByRole('button', { name: 'PORTUGUÊS', exact: true }).click();
  await page.getByRole('button', { name: 'Visualizar final', exact: true }).click();
  await expect(frame.locator('[data-image-slot]')).toHaveCount(0);
  await page.getByRole('button', { name: 'Preview mobile', exact: true }).click();
  const overflow = await frame.locator('body').evaluate((body) => body.scrollWidth > 375);
  expect(overflow).toBe(false);
  await page.getByRole('button', { name: 'Exportar', exact: true }).click();
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Baixar HTML com fotos locais', exact: true }).click();
  const download = await downloaded;
  const html = await readFile((await download.path())!, 'utf8');
  expect(html).toContain(source!);
  expect(html).not.toContain('data-image-slot');
  expect(html).not.toContain('<script');
  expect(html).not.toContain('Clique para adicionar');
  await page.getByRole('button', { name: 'Fechar', exact: true }).click();
  await expect(page.getByText('Salvo neste navegador', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Layout com fotos', exact: true }).click();
  await expect(frame.getByRole('img', { name: 'Foto carregada do computador' })).toHaveAttribute('src', source!);
  await page.getByLabel('Assunto', { exact: true }).fill('Última edição antes da recarga');
  await page.reload();
  await page.getByRole('button', { name: 'Layout com fotos', exact: true }).click();
  await expect(page.getByLabel('Assunto', { exact: true })).toHaveValue('Última edição antes da recarga');
  await expect(frame.getByRole('img', { name: 'Foto carregada do computador' })).toHaveAttribute('src', source!);
  await frame.getByRole('button', { name: 'Trocar foto do produto' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Link da web', exact: true }).click();
  await page.getByLabel('URL · imagem principal', { exact: true }).fill('https://images.example.com/material.png');
  await page.getByRole('button', { name: 'Usar imagem da web', exact: true }).click();
  await expect(page.getByText('Imagem da web aplicada.')).toBeVisible();
  await page.getByRole('button', { name: 'Concluir', exact: true }).click();
  await expect(frame.getByRole('img', { name: 'Foto carregada do computador' })).toHaveAttribute('src', 'https://images.example.com/material.png');
  expect(errors).toEqual([]);
});

test('existing localStorage campaigns migrate to photo-capable storage without losing edits', async ({ page }) => {
  const campaign = createCampaign({ title: 'Campanha anterior', template: 'notice', blocks: [{ id: 'body', enabled: true }] });
  campaign.content.pt.headline = 'Texto preservado';
  const previous = { version: 2, campaigns: [campaign], brand: defaultBrand };
  await page.addInitScript((value) => localStorage.setItem('granistone-mail-studio:v2', JSON.stringify(value)), previous);
  await page.goto('/');
  await page.getByRole('button', { name: 'Campanha anterior', exact: true }).click();
  await expect(page.getByLabel('Headline', { exact: true })).toHaveValue('Texto preservado');
  await page.getByLabel('Headline', { exact: true }).fill('Texto novo preservado');
  await expect(page.getByText('Salvo neste navegador', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Campanha anterior', exact: true }).click();
  await expect(page.getByLabel('Headline', { exact: true })).toHaveValue('Texto novo preservado');
});
