'use client';
import { useContext, useEffect, useState } from 'react';
import { Plus, Shield, Users } from 'lucide-react';
import { online } from '@/lib/online';
import type { MemberRole, WorkspaceMember } from '@/types/collaboration';
import { CollaborationContext } from '@/lib/use-collaboration';
import { Field, Modal, Select } from './ui';
const roles = { admin: 'Administrador', editor: 'Editor', viewer: 'Visualizador' };
export default function WorkspaceMembers({ onClose }: { onClose: () => void }) {
  const { session, presence } = useContext(CollaborationContext);
  const [members, setMembers] = useState<WorkspaceMember[]>([]), [events, setEvents] = useState<Awaited<ReturnType<typeof online.members.events>>>([]);
  const [adding, setAdding] = useState(false), [removing, setRemoving] = useState<WorkspaceMember>();
  const [email, setEmail] = useState(''), [name, setName] = useState(''), [role, setRole] = useState<MemberRole>('editor');
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const load = async () => { const [rows, audit] = await Promise.all([online.members.list(), online.members.events()]); setMembers(rows); setEvents(audit); };
  useEffect(() => { let alive = true; Promise.all([online.members.list(), online.members.events()]).then(([rows, audit]) => { if (alive) { setMembers(rows); setEvents(audit); } }).catch(caught => { if (alive) setError(caught.message); }); return () => { alive = false; }; }, []);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'A ação não foi concluída.'); } finally { setBusy(false); } }
  return <Modal title="Membros do workspace" onClose={onClose} wide><div className="members-heading"><div><Users size={20} /><span>{members.length} membros · Granistone</span></div><button className="button primary" disabled={busy} onClick={() => setAdding(true)}><Plus size={16} /> Adicionar membro</button></div><p className="muted">Autorize o e-mail utilizado pela pessoa para entrar com ChatGPT.</p>
    {error && <p className="alert" role="alert">{error}</p>}
    <div className="members-list">{members.map(m => { const current = presence.filter(p => p.email === m.email); return <article key={m.id} className="member-row"><span className="member-avatar">{(m.name || m.email).slice(0, 2).toUpperCase()}</span><div><strong>{m.name || m.email.split('@')[0]} {m.email === session?.email && <small>Você</small>}</strong><span>{m.email}</span><small>{m.owner ? 'Acesso de emergência' : m.created_at ? `Entrada em ${new Date(m.created_at).toLocaleDateString('pt-BR')}` : ''} · {m.status === 'disabled' ? 'Acesso desativado' : current.length ? current.every(p => p.state === 'away') ? 'Ausente' : 'Online' : 'Offline'}</small>{current.map((p, i) => <small key={i}>{p.editing ? 'Editando' : 'Visualizando'} {p.resourceName || p.location}</small>)}{!current.length && m.last_seen_at && <small>Último acesso: {new Date(m.last_seen_at).toLocaleString('pt-BR')}</small>}</div>{m.owner ? <span className="member-owner"><Shield size={15} /> Administrador</span> : <div className="member-actions"><select aria-label={`Função de ${m.email}`} value={m.role} disabled={busy} onChange={e => void run(() => online.members.change(m.id, { role: e.target.value }))}>{Object.entries(roles).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select><button className="text-button" disabled={busy} onClick={() => void run(() => online.members.change(m.id, { status: m.status === 'active' ? 'disabled' : 'active' }))}>{m.status === 'active' ? 'Desativar acesso' : 'Ativar acesso'}</button><button className="text-button danger" disabled={busy} onClick={() => setRemoving(m)}>Remover acesso</button></div>}</article>; })}</div>
    {!!events.length && <details className="member-audit"><summary>Histórico de membros</summary>{events.map(e => <p key={e.id}><strong>{e.actor_email}</strong> · {e.action === 'added' ? 'Adicionou' : e.action === 'removed' ? 'Removeu acesso de' : 'Atualizou'} {e.member_email || e.member_id}{e.new_role && ` · ${e.new_role}`}<small>{new Date(e.created_at).toLocaleString('pt-BR')}</small></p>)}</details>}
    {adding && <Modal title="Adicionar ao workspace" onClose={() => setAdding(false)}><form onSubmit={e => { e.preventDefault(); void run(async () => { await online.members.add(email, role, name); setAdding(false); setEmail(''); setName(''); }); }}><Field label="Nome · opcional" value={name} onChange={e => setName(e.target.value)} /><Field label="E-mail" type="email" required autoFocus value={email} placeholder="flavia@granistone.com.br" onChange={e => setEmail(e.target.value)} /><Select label="Permissão" value={role} onChange={e => setRole(e.target.value as MemberRole)}>{Object.entries(roles).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</Select>{error && <p className="alert" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button" onClick={() => setAdding(false)}>Cancelar</button><button className="button primary" disabled={busy || !email.trim()}>Adicionar membro</button></div></form></Modal>}
    {removing && <Modal title="Remover acesso" onClose={() => setRemoving(undefined)}><p>Remover acesso de <strong>{removing.email}</strong>?</p><p className="muted">Essa pessoa não poderá mais acessar o workspace. Suas campanhas, alterações e autoria serão preservadas no histórico.</p>{error && <p className="alert" role="alert">{error}</p>}<div className="modal-actions"><button className="button" onClick={() => setRemoving(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => void run(async () => { await online.members.remove(removing.id); setRemoving(undefined); })}>Remover acesso</button></div></Modal>}
  </Modal>;
}
